// Bilingual text for tutorial-maf lesson ("how to read" pedagogical style)

import { getLang } from '../../engine/i18n';
import type { Lang, SubtitleCue } from '../../engine/types';

export interface SceneText {
  id: string;
  narration: string;
  subtitleCues: SubtitleCue[];
  topic: string;
  title: string;
  [field: string]: string | SubtitleCue[];
}

export interface LessonText {
  lessonTitle: string;
  lessonSubtitle: string;
  [key: string]: string | SceneText;
}

export const text: Record<Lang, LessonText> = {
  es: {
    lessonTitle: 'Tutorial MAF: Cómo se lee',
    lessonSubtitle: 'Guía paso a paso de Masked Autoregressive Flow',

    // S1 — Context
    scene1: {
      id: 'Contexto',
      narration: 'Antes de sumergirnos en las ecuaciones, situémonos. En el PS1 aprendimos modelos autoregresivos: densidad exacta pero muestreo secuencial. En el PS2, VAEs: muestreo rápido pero densidad aproximada. Normalizing flows prometen lo mejor de ambos mundos: densidad exacta y muestreo, gracias a transformaciones invertibles.',
      subtitleCues: [
        { time: 0.0, text: 'Situémonos antes de las ecuaciones' },
        { time: 0.12, text: 'PS1: Autoregresivos — densidad exacta, muestreo lento' },
        { time: 0.25, text: 'PS2: VAEs — muestreo rápido, densidad aproximada' },
        { time: 0.38, text: 'PS3: Flows — lo mejor de ambos mundos' },
        { time: 0.5, text: 'Transformaciones invertibles: z ↔ x' },
        { time: 0.62, text: 'Densidad exacta + muestreo' },
        { time: 0.75, text: 'La idea: deformar una Gaussiana simple' },
        { time: 0.88, text: 'Veamos las ecuaciones paso a paso' },
      ],
      topic: 'Contexto de normalizing flows en el curso. PS1 autoregresivos, PS2 VAEs, PS3 flows. Transformaciones invertibles para densidad exacta.',
      title: '¿Por qué Normalizing Flows?',
      ps1Label: 'PS1: Autoregresivos',
      ps1Pro: 'Densidad exacta',
      ps1Con: 'Muestreo secuencial',
      ps2Label: 'PS2: VAEs',
      ps2Pro: 'Muestreo rápido',
      ps2Con: 'Densidad aproximada',
      ps3Label: 'PS3: Flows',
      ps3Pro: 'Densidad exacta + Muestreo',
      ps3Con: 'Requiere invertibilidad',
      flowDiagram: 'p(z) → f → p(x)',
      bestOfBoth: '¿Lo mejor de ambos mundos?',
    },

    // S2 — Equation 1: Autoregressive factorization
    scene2: {
      id: 'Ecuación 1',
      narration: 'La primera ecuación es la factorización autoregresiva. Se lee así: la probabilidad conjunta de x es igual al producto de las probabilidades condicionales de cada componente, donde cada componente depende de todas las anteriores. Esta no es una suposición — es un hecho matemático, la regla de la cadena de probabilidad.',
      subtitleCues: [
        { time: 0.0, text: 'Ecuación 1: Factorización autoregresiva' },
        { time: 0.12, text: 'p(x) = producto de condicionales' },
        { time: 0.25, text: 'Cada componente depende de las anteriores' },
        { time: 0.38, text: 'Símbolo por símbolo...' },
        { time: 0.5, text: 'Ejemplo: n = 2' },
        { time: 0.62, text: 'p(x₁, x₂) = p(x₁) · p(x₂|x₁)' },
        { time: 0.75, text: 'Regla de la cadena — hecho matemático' },
        { time: 0.88, text: 'No es una suposición, es siempre verdad' },
      ],
      topic: 'Factorización autoregresiva. p(x) = Π p(xᵢ|x<i). Regla de la cadena de probabilidad. Hecho matemático, no suposición.',
      title: 'Ecuación 1: Factorización',
      howToRead: '"La probabilidad de x es el producto de la probabilidad de cada componente, condicionada en todas las anteriores."',
      sym1label: 'p(x)',
      sym1desc: 'Probabilidad conjunta del vector x',
      sym2label: '\\prod_{i=1}^{n}',
      sym2desc: 'Producto para i = 1, 2, ..., n',
      sym3label: 'p(x_i \\mid x_{<i})',
      sym3desc: 'Prob. de xᵢ dado todo lo anterior',
      sym4label: 'x_{<i}',
      sym4desc: 'Componentes x₁, x₂, ..., xᵢ₋₁',
      exampleTitle: 'Ejemplo: n = 2',
      insight: 'Regla de la cadena — hecho matemático, no suposición',
    },

    // S3 — What is alpha_i?
    scene3: {
      id: 'Qué es αᵢ',
      narration: 'Antes de ver los mapeos, entendamos alfa-i. El modelo predice alfa-i, un número real cualquiera. Luego sigma-i es igual a exponencial de alfa-i. ¿Por qué? Porque la exponencial siempre es positiva, así que sigma queda automáticamente positiva. No necesitamos restricciones extra.',
      subtitleCues: [
        { time: 0.0, text: 'Un parámetro clave: αᵢ' },
        { time: 0.12, text: 'σᵢ = exp(αᵢ)' },
        { time: 0.25, text: 'αᵢ puede ser cualquier número real' },
        { time: 0.38, text: 'exp() lo convierte en positivo' },
        { time: 0.5, text: 'Símbolo por símbolo...' },
        { time: 0.62, text: 'αᵢ ∈ ℝ → σᵢ > 0 automáticamente' },
        { time: 0.75, text: 'exp(αᵢ)² = exp(2αᵢ) — la varianza' },
        { time: 0.88, text: 'exp hace positivo todo automáticamente' },
      ],
      topic: 'Parámetro αᵢ. σᵢ = exp(αᵢ). La exponencial garantiza σ > 0. αᵢ ∈ ℝ libre, σᵢ siempre positiva.',
      title: '¿Qué es αᵢ?',
      howToRead: '"Sigma sub i es igual a e elevado a alfa sub i."',
      sym1label: '\\alpha_i',
      sym1desc: 'Log-escala predicha por la red (ℝ)',
      sym2label: '\\exp(\\alpha_i)',
      sym2desc: 'Escala σᵢ, siempre > 0',
      sym3label: '\\exp(\\alpha_i)^2',
      sym3desc: 'Varianza σᵢ², siempre > 0',
      rangeAlpha: 'αᵢ ∈ (-∞, +∞)',
      rangeSigma: 'σᵢ ∈ (0, +∞)',
      insight: 'exp lo hace positivo automáticamente',
    },

    // S4 — Forward and Inverse mappings
    scene4: {
      id: 'Forward e Inverse',
      narration: 'Ahora los dos mapeos clave. El mapeo forward va de z a x: toma un z simple, lo escala por sigma y le suma mu. El mapeo inverso va de x a z: resta mu y divide entre sigma. Son exactamente inversos el uno del otro. ¿Te recuerda algo? Es la misma reparametrización del VAE del PS2.',
      subtitleCues: [
        { time: 0.0, text: 'Dos mapeos: forward e inverse' },
        { time: 0.12, text: 'Forward: z → x' },
        { time: 0.25, text: 'xᵢ = μᵢ + zᵢ · exp(αᵢ)' },
        { time: 0.38, text: 'Inverse: x → z' },
        { time: 0.5, text: 'zᵢ = (xᵢ − μᵢ) / exp(αᵢ)' },
        { time: 0.62, text: 'Son exactamente inversos' },
        { time: 0.75, text: '¡Reparametrización del VAE! (PS2)' },
        { time: 0.88, text: 'z simple ↔ x complejo' },
      ],
      topic: 'Mapeo forward z→x: xᵢ = μᵢ + zᵢ·exp(αᵢ). Mapeo inverso x→z: zᵢ = (xᵢ − μᵢ)/exp(αᵢ). Reparametrización del VAE.',
      title: 'Forward e Inverse',
      forwardTitle: 'Forward (z → x)',
      inverseTitle: 'Inverse (x → z)',
      forwardRead: '"xᵢ es mu-i más z-i por sigma-i"',
      inverseRead: '"zᵢ es x-i menos mu-i, dividido entre sigma-i"',
      zSpace: 'Espacio z (simple)',
      xSpace: 'Espacio x (complejo)',
      insight: 'Reparametrización del PS2 (VAE trick)',
    },

    // S5 — Sequential vs Parallel asymmetry
    scene5: {
      id: 'Secuencial vs Paralelo',
      narration: 'Aquí está la asimetría clave de MAF. El mapeo forward es secuencial: para calcular x-i, necesitas mu-i y sigma-i, que dependen de x anteriores. Pero el inverso es paralelo: dado x completo, MADE calcula todos los mu y sigma de golpe, y luego cada z-i se obtiene en paralelo. MAF entrena con el inverse rápido.',
      subtitleCues: [
        { time: 0.0, text: 'La asimetría clave de MAF' },
        { time: 0.12, text: 'Forward (z→x): secuencial' },
        { time: 0.25, text: 'Cada xᵢ necesita las anteriores' },
        { time: 0.38, text: 'n pasadas: lento para muestreo' },
        { time: 0.5, text: 'Inverse (x→z): paralelo' },
        { time: 0.62, text: 'x completo → MADE → todos μᵢ, αᵢ' },
        { time: 0.75, text: '1 pasada: rápido para entrenamiento' },
        { time: 0.88, text: 'MAF: inverse rápido, forward lento' },
      ],
      topic: 'Asimetría MAF. Forward z→x secuencial (n pasadas). Inverse x→z paralelo (1 pasada via MADE). MAF entrena con inverse rápido.',
      title: 'Secuencial vs Paralelo',
      forwardLabel: 'Forward (z → x): Secuencial',
      inverseLabel: 'Inverse (x → z): Paralelo',
      forwardBadge: 'n pasadas',
      inverseBadge: '1 pasada',
      step: 'paso',
      madeLabel: 'MADE',
      allAtOnce: 'Todos z a la vez',
      insight: 'MAF: inverse rápido (entrenamiento), forward lento (muestreo)',
    },

    // Jacobian Intuition — Why we need det J
    sceneJacIntuition: {
      id: 'Intuición Jacobiana',
      narration: 'Antes de la ecuación del cambio de variables, una pregunta clave: ¿por qué necesitamos el determinante del Jacobiano? Cuando transformamos una variable, la densidad no se conserva automáticamente. Imagina que estiras un globo: donde se estira más, la densidad baja. Donde se comprime, la densidad sube. El determinante del Jacobiano es exactamente el factor de corrección que mide cuánto estira o comprime la transformación en cada punto.',
      subtitleCues: [
        { time: 0.0, text: 'Intuición: ¿por qué det J?' },
        { time: 0.12, text: 'Pregunta: ¿por qué necesitamos det J en la fórmula?' },
        { time: 0.24, text: 'Espacio z: densidad uniforme' },
        { time: 0.36, text: 'Transformación: estira el espacio' },
        { time: 0.48, text: 'Espacio x: densidad NO uniforme' },
        { time: 0.58, text: 'Donde estira más → densidad baja' },
        { time: 0.68, text: 'Donde comprime → densidad sube' },
        { time: 0.78, text: 'det J mide cuánto estira en cada punto' },
        { time: 0.88, text: 'det J = factor de corrección de volumen' },
      ],
      topic: 'Intuición del Jacobiano. Al transformar, la densidad no se conserva. det J corrige por el cambio de volumen.',
      title: 'Intuición: ¿Por qué det J?',
      question: '¿Por qué necesitamos det J en la fórmula?',
      zSpaceLabel: 'Espacio z',
      xSpaceLabel: 'Espacio x',
      stretchArrow: 'estira',
      densityHigh: 'Densidad alta',
      densityLow: 'Densidad baja',
      jacobianMeasures: 'det J mide cuánto estira en cada punto',
      correctionFormula: 'Factor de corrección de volumen',
      insight: 'det J corrige por el cambio de volumen',
    },

    // S6 — Equation 2: Change of variables (multi-layer)
    scene6: {
      id: 'Ecuación 2',
      narration: 'La ecuación de cambio de variables multi-capa se lee así: el log de la probabilidad de x es igual al log de la probabilidad base evaluada en z-cero, más la suma de los log-determinantes de cada capa. Cada capa transforma un poco, y acumulamos los log-determinantes. ¿Por qué una suma? Porque al componer funciones invertibles, el Jacobiano total es el producto de los Jacobianos individuales, y al tomar log, el producto se convierte en suma. Nota: fₖ denota la función k-ésima, no una potencia.',
      subtitleCues: [
        { time: 0.0, text: 'Ecuación 2: Cambio de variables' },
        { time: 0.1, text: 'Multi-capa: K transformaciones' },
        { time: 0.2, text: 'log p(x) = log p(z₀) + Σ log|det Jₖ|' },
        { time: 0.3, text: 'Símbolo por símbolo...' },
        { time: 0.4, text: 'Pipeline: x → inversa₁ → ... → z₀' },
        { time: 0.5, text: 'Cada capa aporta un log|det|' },
        { time: 0.6, text: 'Composición → producto de dets → suma de logs' },
        { time: 0.7, text: 'Nota: fₖ = función k-ésima (no potencia)' },
        { time: 0.8, text: 'Composición de flows invertibles' },
        { time: 0.9, text: 'Producto → suma: la clave del multi-capa' },
      ],
      topic: 'Cambio de variables multi-capa. log p(x) = log p(z₀) + Σ log|det Jₖ⁻¹|. Pipeline de transformaciones invertibles.',
      title: 'Ecuación 2: Cambio de Variables',
      howToRead: '"Log p de x es log p base evaluada en z-cero, más la suma de los log-determinantes de cada capa inversa."',
      sym1label: '\\log p(\\mathbf{x})',
      sym1desc: 'Log-verosimilitud del dato x',
      sym2label: '\\log p(\\mathbf{z}_0)',
      sym2desc: 'Log-prob. base (Gaussiana) en z₀',
      sym3label: 'K',
      sym3desc: 'Número de capas del flow',
      sym4label: '\\log|\\det J_k^{-1}|',
      sym4desc: 'Log-det Jacobiano de la inversa k',
      sym5label: '\\mathbf{z}_0',
      sym5desc: 'Resultado tras K inversas',
      sym6label: 'J_k^{-1}',
      sym6desc: 'Jacobiano de la capa inversa k',
      sym7label: '\\sum_{k=1}^{K}',
      sym7desc: 'Suma sobre las K capas',
      pipelineLabel: 'Pipeline',
      sumExplanation: 'Composición → producto de dets → suma de log-dets',
      notationNote: 'Nota: fₖ es la función k-ésima, no f elevado a k',
      insight: 'Producto de dets → suma de logs',
    },

    // S7 — Equation 3: Triangular Jacobian
    scene7: {
      id: 'Ecuación 3',
      narration: 'La ecuación tres es la joya de MAF. El log del determinante del Jacobiano es simplemente menos la suma de los alfa-i. ¿Por qué es triangular? Por la estructura autoregresiva: z-i solo depende de x-uno hasta x-i, así que la derivada parcial de z-i respecto a x-j es cero cuando j es mayor que i. Eso fuerza ceros arriba de la diagonal. El determinante es entonces solo el producto de la diagonal, que es uno entre sigma-i. De O de n cúbico a O de n.',
      subtitleCues: [
        { time: 0.0, text: 'Ecuación 3: Jacobiano triangular' },
        { time: 0.1, text: 'log|det J| = −Σαᵢ' },
        { time: 0.2, text: '¡Así de simple!' },
        { time: 0.3, text: 'Símbolo por símbolo...' },
        { time: 0.4, text: '¿Por qué triangular? → estructura autoregresiva' },
        { time: 0.5, text: 'zᵢ depende de x₁...xᵢ → ∂zᵢ/∂xⱼ = 0 para j > i' },
        { time: 0.6, text: 'Jacobiano triangular inferior' },
        { time: 0.7, text: 'det = producto de la diagonal' },
        { time: 0.8, text: 'Diagonal = 1/σᵢ = exp(−αᵢ)' },
        { time: 0.9, text: 'O(n³) → O(n) — enorme ganancia' },
      ],
      topic: 'Jacobiano triangular. log|det J| = −Σαᵢ. Diagonal = 1/σᵢ. De O(n³) a O(n). Triangular por estructura autoregresiva.',
      title: 'Ecuación 3: Jacobiano Triangular',
      howToRead: '"El log del valor absoluto del determinante del Jacobiano es menos la suma de los alfa-i."',
      sym1label: '\\log|\\det J|',
      sym1desc: 'Log-determinante del Jacobiano',
      sym2label: '-\\sum_i \\alpha_i',
      sym2desc: 'Menos la suma de log-escalas',
      sym3label: '\\alpha_i',
      sym3desc: 'Log-escala de la componente i',
      matrixTitle: 'Jacobiano 3×3',
      diagLabel: 'Diagonal: 1/σᵢ',
      zerosLabel: 'Ceros (triangular)',
      whyTriangular1: 'Autoregresivo: zᵢ solo depende de x₁...xᵢ',
      whyTriangular2: '→ ∂zᵢ/∂xⱼ = 0 para j > i → triangular',
      step1: '\\det J = \\prod_i \\frac{1}{\\sigma_i}',
      step2: '\\log|\\det J| = \\sum_i \\log \\frac{1}{\\sigma_i}',
      step3: '= -\\sum_i \\log \\sigma_i = -\\sum_i \\alpha_i',
      insight: 'O(n³) → O(n)',
    },

    // S8 — MAF Architecture
    scene8: {
      id: 'Arquitectura',
      narration: 'La arquitectura completa: un bloque MADE toma la entrada y produce mu y alfa gracias a sus capas enmascaradas. Luego una capa de permutación mezcla el orden. Repetimos K veces. En el código del PS3, el flow va de z-cero Gaussiana, pasando por cinco bloques MADE con permutaciones intercaladas, hasta llegar a x.',
      subtitleCues: [
        { time: 0.0, text: 'Arquitectura completa de MAF' },
        { time: 0.12, text: 'Bloque MADE: entrada → (μ, α)' },
        { time: 0.25, text: 'Capas enmascaradas: autoregresividad' },
        { time: 0.38, text: 'Mini máscara: verde = permitido, gris = bloqueado' },
        { time: 0.5, text: 'PermuteLayer: cambia el orden' },
        { time: 0.62, text: 'Repetir K veces: MADE + Permute' },
        { time: 0.75, text: 'Pipeline: z₀ → MADE₁ → P → ... → x' },
        { time: 0.88, text: 'En el PS3: K = 5 bloques' },
      ],
      topic: 'Arquitectura MAF. MADE con máscaras → (μ, α). PermuteLayer intercalada. Pipeline K capas. PS3: K=5.',
      title: 'Arquitectura MAF',
      madeBlock: 'MADE',
      inputLabel: 'Entrada',
      outputLabel: '(μ, α)',
      maskAllowed: 'Permitido',
      maskBlocked: 'Bloqueado',
      permuteLabel: 'Permute',
      pipelineTitle: 'Pipeline completo (PS3)',
      gaussianLabel: 'z₀ ~ N(0, I)',
      dataLabel: 'x',
    },

    // S9 — Recap
    scene9: {
      id: 'Resumen',
      narration: 'Resumen: para calcular log p de x, aplicamos las inversas capa por capa hasta obtener z-cero, evaluamos la Gaussiana base, y sumamos los log-determinantes. Cada log-det es solo menos la suma de alfas. El ejercicio uno del PS3 implementa esto en tres apartados: forward, inverse, y log-prob. Ya tienes todo lo que necesitas.',
      subtitleCues: [
        { time: 0.0, text: 'Resumen: cómo calcular log p(x)' },
        { time: 0.12, text: 'Paso 1: Aplicar inversas capa por capa' },
        { time: 0.25, text: 'Paso 2: Obtener z₀ (espacio base)' },
        { time: 0.38, text: 'Paso 3: Evaluar log p(z₀) — Gaussiana' },
        { time: 0.5, text: 'Paso 4: Sumar Σ log|det Jₖ⁻¹| = −Σαᵢ' },
        { time: 0.62, text: 'PS3 Ejercicio 1: tres apartados' },
        { time: 0.75, text: 'a) forward, b) inverse, c) log_prob' },
        { time: 0.88, text: '¡Ya tienes todo lo que necesitas!' },
      ],
      topic: 'Resumen. 4 pasos para log p(x). PS3 Ex1: forward, inverse, log_prob. Conceptos clave cubiertos.',
      title: 'Resumen y Resultados',
      step1: '1. Aplicar inversas: x → z_{K-1} → ... → z₀',
      step2: '2. Evaluar log p(z₀) — Gaussiana estándar',
      step3: '3. Acumular log|det| = −Σαᵢ por capa',
      step4: '4. Sumar: log p(x) = log p(z₀) + Σ log|det|',
      ps3Title: 'PS3 Ejercicio 1',
      partA: 'a) forward (z → x)',
      partB: 'b) inverse (x → z)',
      partC: 'c) log_prob',
      concept1: 'Factorización autoregresiva',
      concept2: 'αᵢ y la reparametrización',
      concept3: 'Forward vs Inverse (asimetría)',
      concept4: 'Cambio de variables multi-capa',
      concept5: 'Jacobiano triangular → O(n)',
    },
  },

  en: {
    lessonTitle: 'MAF Tutorial: How to Read',
    lessonSubtitle: 'Step-by-step guide to Masked Autoregressive Flow',

    // S1 — Context
    scene1: {
      id: 'Context',
      narration: 'Before diving into the equations, let us get our bearings. In PS1 we learned autoregressive models: exact density but sequential sampling. In PS2, VAEs: fast sampling but approximate density. Normalizing flows promise the best of both worlds: exact density and sampling, thanks to invertible transformations.',
      subtitleCues: [
        { time: 0.0, text: 'Let us get our bearings before the equations' },
        { time: 0.12, text: 'PS1: Autoregressive — exact density, slow sampling' },
        { time: 0.25, text: 'PS2: VAEs — fast sampling, approximate density' },
        { time: 0.38, text: 'PS3: Flows — best of both worlds' },
        { time: 0.5, text: 'Invertible transformations: z ↔ x' },
        { time: 0.62, text: 'Exact density + sampling' },
        { time: 0.75, text: 'The idea: warp a simple Gaussian' },
        { time: 0.88, text: 'Let us read the equations step by step' },
      ],
      topic: 'Context of normalizing flows in the course. PS1 autoregressive, PS2 VAEs, PS3 flows. Invertible transformations for exact density.',
      title: 'Why Normalizing Flows?',
      ps1Label: 'PS1: Autoregressive',
      ps1Pro: 'Exact density',
      ps1Con: 'Sequential sampling',
      ps2Label: 'PS2: VAEs',
      ps2Pro: 'Fast sampling',
      ps2Con: 'Approximate density',
      ps3Label: 'PS3: Flows',
      ps3Pro: 'Exact density + Sampling',
      ps3Con: 'Requires invertibility',
      flowDiagram: 'p(z) → f → p(x)',
      bestOfBoth: 'Best of both worlds?',
    },

    // S2 — Equation 1: Autoregressive factorization
    scene2: {
      id: 'Equation 1',
      narration: 'The first equation is the autoregressive factorization. It reads: the joint probability of x equals the product of the conditional probabilities of each component, where each component depends on all preceding ones. This is not an assumption — it is a mathematical fact, the chain rule of probability.',
      subtitleCues: [
        { time: 0.0, text: 'Equation 1: Autoregressive factorization' },
        { time: 0.12, text: 'p(x) = product of conditionals' },
        { time: 0.25, text: 'Each component depends on preceding ones' },
        { time: 0.38, text: 'Symbol by symbol...' },
        { time: 0.5, text: 'Example: n = 2' },
        { time: 0.62, text: 'p(x₁, x₂) = p(x₁) · p(x₂|x₁)' },
        { time: 0.75, text: 'Chain rule — mathematical fact' },
        { time: 0.88, text: 'Not an assumption, always true' },
      ],
      topic: 'Autoregressive factorization. p(x) = Π p(xᵢ|x<i). Chain rule of probability. Mathematical fact, not assumption.',
      title: 'Equation 1: Factorization',
      howToRead: '"The probability of x is the product of each component\'s probability, conditioned on all preceding components."',
      sym1label: 'p(x)',
      sym1desc: 'Joint probability of vector x',
      sym2label: '\\prod_{i=1}^{n}',
      sym2desc: 'Product for i = 1, 2, ..., n',
      sym3label: 'p(x_i \\mid x_{<i})',
      sym3desc: 'Prob. of xᵢ given all preceding',
      sym4label: 'x_{<i}',
      sym4desc: 'Components x₁, x₂, ..., xᵢ₋₁',
      exampleTitle: 'Example: n = 2',
      insight: 'Chain rule — mathematical fact, not an assumption',
    },

    // S3 — What is alpha_i?
    scene3: {
      id: 'What is αᵢ',
      narration: 'Before seeing the mappings, let us understand alpha-i. The model predicts alpha-i, any real number. Then sigma-i equals exponential of alpha-i. Why? Because the exponential is always positive, so sigma is automatically positive. No extra constraints needed.',
      subtitleCues: [
        { time: 0.0, text: 'A key parameter: αᵢ' },
        { time: 0.12, text: 'σᵢ = exp(αᵢ)' },
        { time: 0.25, text: 'αᵢ can be any real number' },
        { time: 0.38, text: 'exp() makes it positive' },
        { time: 0.5, text: 'Symbol by symbol...' },
        { time: 0.62, text: 'αᵢ ∈ ℝ → σᵢ > 0 automatically' },
        { time: 0.75, text: 'exp(αᵢ)² = exp(2αᵢ) — the variance' },
        { time: 0.88, text: 'exp makes everything positive automatically' },
      ],
      topic: 'Parameter αᵢ. σᵢ = exp(αᵢ). Exponential guarantees σ > 0. αᵢ ∈ ℝ free, σᵢ always positive.',
      title: 'What is αᵢ?',
      howToRead: '"Sigma sub i equals e raised to alpha sub i."',
      sym1label: '\\alpha_i',
      sym1desc: 'Log-scale predicted by the network (ℝ)',
      sym2label: '\\exp(\\alpha_i)',
      sym2desc: 'Scale σᵢ, always > 0',
      sym3label: '\\exp(\\alpha_i)^2',
      sym3desc: 'Variance σᵢ², always > 0',
      rangeAlpha: 'αᵢ ∈ (-∞, +∞)',
      rangeSigma: 'σᵢ ∈ (0, +∞)',
      insight: 'exp makes it positive automatically',
    },

    // S4 — Forward and Inverse mappings
    scene4: {
      id: 'Forward and Inverse',
      narration: 'Now the two key mappings. The forward mapping goes from z to x: take a simple z, scale it by sigma and add mu. The inverse mapping goes from x to z: subtract mu and divide by sigma. They are exact inverses of each other. Ring a bell? It is the same reparameterization trick from the PS2 VAE.',
      subtitleCues: [
        { time: 0.0, text: 'Two mappings: forward and inverse' },
        { time: 0.12, text: 'Forward: z → x' },
        { time: 0.25, text: 'xᵢ = μᵢ + zᵢ · exp(αᵢ)' },
        { time: 0.38, text: 'Inverse: x → z' },
        { time: 0.5, text: 'zᵢ = (xᵢ − μᵢ) / exp(αᵢ)' },
        { time: 0.62, text: 'They are exact inverses' },
        { time: 0.75, text: 'VAE reparameterization trick! (PS2)' },
        { time: 0.88, text: 'Simple z ↔ complex x' },
      ],
      topic: 'Forward mapping z→x: xᵢ = μᵢ + zᵢ·exp(αᵢ). Inverse mapping x→z: zᵢ = (xᵢ − μᵢ)/exp(αᵢ). VAE reparameterization.',
      title: 'Forward and Inverse',
      forwardTitle: 'Forward (z → x)',
      inverseTitle: 'Inverse (x → z)',
      forwardRead: '"xᵢ is mu-i plus z-i times sigma-i"',
      inverseRead: '"zᵢ is x-i minus mu-i, divided by sigma-i"',
      zSpace: 'z-space (simple)',
      xSpace: 'x-space (complex)',
      insight: 'Reparameterization from PS2 (VAE trick)',
    },

    // S5 — Sequential vs Parallel asymmetry
    scene5: {
      id: 'Sequential vs Parallel',
      narration: 'Here is the key asymmetry of MAF. The forward mapping is sequential: to compute x-i, you need mu-i and sigma-i, which depend on previous x values. But the inverse is parallel: given the complete x, MADE computes all mu and sigma at once, and then each z-i is obtained in parallel. MAF trains with the fast inverse.',
      subtitleCues: [
        { time: 0.0, text: 'The key asymmetry of MAF' },
        { time: 0.12, text: 'Forward (z→x): sequential' },
        { time: 0.25, text: 'Each xᵢ needs the previous ones' },
        { time: 0.38, text: 'n passes: slow for sampling' },
        { time: 0.5, text: 'Inverse (x→z): parallel' },
        { time: 0.62, text: 'Full x → MADE → all μᵢ, αᵢ' },
        { time: 0.75, text: '1 pass: fast for training' },
        { time: 0.88, text: 'MAF: fast inverse, slow forward' },
      ],
      topic: 'MAF asymmetry. Forward z→x sequential (n passes). Inverse x→z parallel (1 pass via MADE). MAF trains with fast inverse.',
      title: 'Sequential vs Parallel',
      forwardLabel: 'Forward (z → x): Sequential',
      inverseLabel: 'Inverse (x → z): Parallel',
      forwardBadge: 'n passes',
      inverseBadge: '1 pass',
      step: 'step',
      madeLabel: 'MADE',
      allAtOnce: 'All z at once',
      insight: 'MAF: fast inverse (training), slow forward (sampling)',
    },

    // Jacobian Intuition — Why we need det J
    sceneJacIntuition: {
      id: 'Jacobian Intuition',
      narration: 'Before the change of variables equation, a key question: why do we need the Jacobian determinant? When we transform a variable, the density is not automatically preserved. Imagine stretching a balloon: where it stretches more, the density drops. Where it compresses, the density rises. The Jacobian determinant is exactly the correction factor that measures how much the transformation stretches or compresses at each point.',
      subtitleCues: [
        { time: 0.0, text: 'Intuition: why det J?' },
        { time: 0.12, text: 'Question: why do we need det J in the formula?' },
        { time: 0.24, text: 'z-space: uniform density' },
        { time: 0.36, text: 'Transformation: stretches space' },
        { time: 0.48, text: 'x-space: NON-uniform density' },
        { time: 0.58, text: 'Where it stretches more → density drops' },
        { time: 0.68, text: 'Where it compresses → density rises' },
        { time: 0.78, text: 'det J measures how much it stretches at each point' },
        { time: 0.88, text: 'det J = volume correction factor' },
      ],
      topic: 'Jacobian intuition. When transforming, density is not preserved. det J corrects for the volume change.',
      title: 'Intuition: Why det J?',
      question: 'Why do we need det J in the formula?',
      zSpaceLabel: 'z-space',
      xSpaceLabel: 'x-space',
      stretchArrow: 'stretches',
      densityHigh: 'High density',
      densityLow: 'Low density',
      jacobianMeasures: 'det J measures how much it stretches at each point',
      correctionFormula: 'Volume correction factor',
      insight: 'det J corrects for the volume change',
    },

    // S6 — Equation 2: Change of variables (multi-layer)
    scene6: {
      id: 'Equation 2',
      narration: 'The multi-layer change of variables equation reads: the log probability of x equals the log of the base probability evaluated at z-zero, plus the sum of the log-determinants of each layer. Each layer transforms a little, and we accumulate the log-determinants. Why a sum? Because composing invertible functions means the total Jacobian is the product of individual Jacobians, and taking the log turns the product into a sum. Note: fₖ denotes the k-th function, not an exponent.',
      subtitleCues: [
        { time: 0.0, text: 'Equation 2: Change of variables' },
        { time: 0.1, text: 'Multi-layer: K transformations' },
        { time: 0.2, text: 'log p(x) = log p(z₀) + Σ log|det Jₖ|' },
        { time: 0.3, text: 'Symbol by symbol...' },
        { time: 0.4, text: 'Pipeline: x → inverse₁ → ... → z₀' },
        { time: 0.5, text: 'Each layer contributes a log|det|' },
        { time: 0.6, text: 'Composition → product of dets → sum of logs' },
        { time: 0.7, text: 'Note: fₖ = k-th function (not an exponent)' },
        { time: 0.8, text: 'Composition of invertible flows' },
        { time: 0.9, text: 'Product → sum: the key to multi-layer' },
      ],
      topic: 'Multi-layer change of variables. log p(x) = log p(z₀) + Σ log|det Jₖ⁻¹|. Pipeline of invertible transformations.',
      title: 'Equation 2: Change of Variables',
      howToRead: '"Log p of x is log base probability at z-zero, plus the sum of log-determinants of each inverse layer."',
      sym1label: '\\log p(\\mathbf{x})',
      sym1desc: 'Log-likelihood of data point x',
      sym2label: '\\log p(\\mathbf{z}_0)',
      sym2desc: 'Log-prob. of base (Gaussian) at z₀',
      sym3label: 'K',
      sym3desc: 'Number of flow layers',
      sym4label: '\\log|\\det J_k^{-1}|',
      sym4desc: 'Log-det Jacobian of inverse layer k',
      sym5label: '\\mathbf{z}_0',
      sym5desc: 'Result after K inverses',
      sym6label: 'J_k^{-1}',
      sym6desc: 'Jacobian of inverse layer k',
      sym7label: '\\sum_{k=1}^{K}',
      sym7desc: 'Sum over K layers',
      pipelineLabel: 'Pipeline',
      sumExplanation: 'Composition → product of dets → sum of log-dets',
      notationNote: 'Note: fₖ is the k-th function, not f raised to k',
      insight: 'Product of dets → sum of logs',
    },

    // S7 — Equation 3: Triangular Jacobian
    scene7: {
      id: 'Equation 3',
      narration: 'Equation three is the gem of MAF. The log of the Jacobian determinant is simply minus the sum of the alpha-i. Why is it triangular? Because of the autoregressive structure: z-i only depends on x-one through x-i, so the partial derivative of z-i with respect to x-j is zero when j is greater than i. That forces zeros above the diagonal. The determinant is then just the product of the diagonal, which is one over sigma-i. From O n-cubed to O n.',
      subtitleCues: [
        { time: 0.0, text: 'Equation 3: Triangular Jacobian' },
        { time: 0.1, text: 'log|det J| = −Σαᵢ' },
        { time: 0.2, text: 'That simple!' },
        { time: 0.3, text: 'Symbol by symbol...' },
        { time: 0.4, text: 'Why triangular? → autoregressive structure' },
        { time: 0.5, text: 'zᵢ depends on x₁...xᵢ → ∂zᵢ/∂xⱼ = 0 for j > i' },
        { time: 0.6, text: 'Lower triangular Jacobian' },
        { time: 0.7, text: 'det = product of diagonal' },
        { time: 0.8, text: 'Diagonal = 1/σᵢ = exp(−αᵢ)' },
        { time: 0.9, text: 'O(n³) → O(n) — huge gain' },
      ],
      topic: 'Triangular Jacobian. log|det J| = −Σαᵢ. Diagonal = 1/σᵢ. From O(n³) to O(n). Triangular due to autoregressive structure.',
      title: 'Equation 3: Triangular Jacobian',
      howToRead: '"The log of the absolute value of the Jacobian determinant is minus the sum of the alpha-i."',
      sym1label: '\\log|\\det J|',
      sym1desc: 'Log-determinant of the Jacobian',
      sym2label: '-\\sum_i \\alpha_i',
      sym2desc: 'Minus the sum of log-scales',
      sym3label: '\\alpha_i',
      sym3desc: 'Log-scale of component i',
      matrixTitle: '3×3 Jacobian',
      diagLabel: 'Diagonal: 1/σᵢ',
      zerosLabel: 'Zeros (triangular)',
      whyTriangular1: 'Autoregressive: zᵢ only depends on x₁...xᵢ',
      whyTriangular2: '→ ∂zᵢ/∂xⱼ = 0 for j > i → triangular',
      step1: '\\det J = \\prod_i \\frac{1}{\\sigma_i}',
      step2: '\\log|\\det J| = \\sum_i \\log \\frac{1}{\\sigma_i}',
      step3: '= -\\sum_i \\log \\sigma_i = -\\sum_i \\alpha_i',
      insight: 'O(n³) → O(n)',
    },

    // S8 — MAF Architecture
    scene8: {
      id: 'Architecture',
      narration: 'The full architecture: a MADE block takes the input and produces mu and alpha through its masked layers. Then a permutation layer shuffles the order. We repeat K times. In the PS3 code, the flow goes from a Gaussian z-zero, through five MADE blocks with interleaved permutations, to x.',
      subtitleCues: [
        { time: 0.0, text: 'Full MAF architecture' },
        { time: 0.12, text: 'MADE block: input → (μ, α)' },
        { time: 0.25, text: 'Masked layers: autoregressive property' },
        { time: 0.38, text: 'Mini mask: green = allowed, gray = blocked' },
        { time: 0.5, text: 'PermuteLayer: changes the ordering' },
        { time: 0.62, text: 'Repeat K times: MADE + Permute' },
        { time: 0.75, text: 'Pipeline: z₀ → MADE₁ → P → ... → x' },
        { time: 0.88, text: 'In PS3: K = 5 blocks' },
      ],
      topic: 'MAF architecture. MADE with masks → (μ, α). Interleaved PermuteLayer. K-layer pipeline. PS3: K=5.',
      title: 'MAF Architecture',
      madeBlock: 'MADE',
      inputLabel: 'Input',
      outputLabel: '(μ, α)',
      maskAllowed: 'Allowed',
      maskBlocked: 'Blocked',
      permuteLabel: 'Permute',
      pipelineTitle: 'Full pipeline (PS3)',
      gaussianLabel: 'z₀ ~ N(0, I)',
      dataLabel: 'x',
    },

    // S9 — Recap
    scene9: {
      id: 'Recap',
      narration: 'Summary: to compute log p of x, we apply the inverses layer by layer to get z-zero, evaluate the base Gaussian, and sum the log-determinants. Each log-det is just minus the sum of alphas. Exercise one of PS3 implements this in three parts: forward, inverse, and log-prob. You have everything you need.',
      subtitleCues: [
        { time: 0.0, text: 'Summary: how to compute log p(x)' },
        { time: 0.12, text: 'Step 1: Apply inverses layer by layer' },
        { time: 0.25, text: 'Step 2: Get z₀ (base space)' },
        { time: 0.38, text: 'Step 3: Evaluate log p(z₀) — Gaussian' },
        { time: 0.5, text: 'Step 4: Sum Σ log|det Jₖ⁻¹| = −Σαᵢ' },
        { time: 0.62, text: 'PS3 Exercise 1: three parts' },
        { time: 0.75, text: 'a) forward, b) inverse, c) log_prob' },
        { time: 0.88, text: 'You have everything you need!' },
      ],
      topic: 'Summary. 4 steps for log p(x). PS3 Ex1: forward, inverse, log_prob. Key concepts covered.',
      title: 'Summary and Results',
      step1: '1. Apply inverses: x → z_{K-1} → ... → z₀',
      step2: '2. Evaluate log p(z₀) — standard Gaussian',
      step3: '3. Accumulate log|det| = −Σαᵢ per layer',
      step4: '4. Sum: log p(x) = log p(z₀) + Σ log|det|',
      ps3Title: 'PS3 Exercise 1',
      partA: 'a) forward (z → x)',
      partB: 'b) inverse (x → z)',
      partC: 'c) log_prob',
      concept1: 'Autoregressive factorization',
      concept2: 'αᵢ and reparameterization',
      concept3: 'Forward vs Inverse (asymmetry)',
      concept4: 'Multi-layer change of variables',
      concept5: 'Triangular Jacobian → O(n)',
    },
  },
};

// ── Questions (bilingual) ──

export const questions: Record<Lang, {
  afterAsymmetry: import('../../engine/types').QuestionData;
  afterJacobian: import('../../engine/types').QuestionData;
}> = {
  es: {
    afterAsymmetry: {
      question: 'Para calcular log p(x) durante el entrenamiento, ¿qué mapeo usa MAF?',
      choices: [
        'Forward (z → x), porque genera muestras',
        'Inverse (x → z), porque transforma datos a espacio base',
        'Ambos por igual',
      ],
      correctIndex: 1,
      hint: 'El entrenamiento necesita evaluar log p(x). ¿Qué mapeo convierte un dato x en z para evaluar la Gaussiana?',
      explanation: 'MAF usa el mapeo inverse (x → z) durante entrenamiento porque es paralelo (una sola pasada de MADE). Luego evalúa log p(z₀) en la Gaussiana base y suma los log-determinantes.',
    },
    afterJacobian: {
      question: '¿Cuál es la ventaja principal del Jacobiano triangular en MAF?',
      choices: [
        'Hace que el flow sea más expresivo',
        'Reduce el costo del determinante de O(n³) a O(n)',
        'Permite usar más capas sin costo adicional',
        'Elimina la necesidad de permutaciones',
      ],
      correctIndex: 1,
      hint: 'Calcular el determinante de una matriz general requiere O(n³). ¿Y de una triangular?',
      explanation: 'El Jacobiano triangular permite calcular el determinante como el producto de la diagonal, reduciendo el costo de O(n³) a O(n). Esto hace que log|det J| = −Σαᵢ sea trivial de computar.',
    },
  },
  en: {
    afterAsymmetry: {
      question: 'To compute log p(x) during training, which mapping does MAF use?',
      choices: [
        'Forward (z → x), because it generates samples',
        'Inverse (x → z), because it transforms data to base space',
        'Both equally',
      ],
      correctIndex: 1,
      hint: 'Training needs to evaluate log p(x). Which mapping converts a data point x into z to evaluate the Gaussian?',
      explanation: 'MAF uses the inverse mapping (x → z) during training because it is parallel (a single MADE pass). Then it evaluates log p(z₀) in the base Gaussian and sums the log-determinants.',
    },
    afterJacobian: {
      question: 'What is the main advantage of the triangular Jacobian in MAF?',
      choices: [
        'It makes the flow more expressive',
        'It reduces the determinant cost from O(n³) to O(n)',
        'It allows more layers without extra cost',
        'It eliminates the need for permutations',
      ],
      correctIndex: 1,
      hint: 'Computing the determinant of a general matrix costs O(n³). What about a triangular one?',
      explanation: 'The triangular Jacobian allows computing the determinant as the product of the diagonal, reducing cost from O(n³) to O(n). This makes log|det J| = −Σαᵢ trivial to compute.',
    },
  },
};

export function tx(scene: string, field: string, ...args: (string | number)[]): string {
  const lang = getLang();
  const sceneObj = text[lang]?.[scene];
  const fallbackObj = text.es[scene];
  const raw = (typeof sceneObj === 'object' && sceneObj !== null ? (sceneObj as Record<string, unknown>)[field] : undefined)
           ?? (typeof fallbackObj === 'object' && fallbackObj !== null ? (fallbackObj as Record<string, unknown>)[field] : undefined)
           ?? '';
  let str = String(raw);
  args.forEach((arg, i) => {
    str = str.replace(`$${i + 1}`, String(arg));
  });
  return str;
}
