// Bilingual text for Change of Variables lesson

import { getLang } from '../../engine/i18n';
import type { Lang, SubtitleCue } from '../../engine/types';

export interface SceneText {
  id: string;
  narration: string;
  subtitleCues: SubtitleCue[];
  topic: string;
  title: string;
  [field: string]: string | SubtitleCue[];
}

export interface LessonText {
  lessonTitle: string;
  lessonSubtitle: string;
  [key: string]: string | SceneText;
}

export const text: Record<Lang, LessonText> = {
  es: {
    lessonTitle: 'Cambio de Variables',
    lessonSubtitle: 'De distribuciones simples a complejas con transformaciones invertibles',
    scene1: {
      id: 'Estirar el espacio',
      narration: 'Piensa en una regla elástica con marcas uniformes. Si comprimes la regla a la mitad, las marcas se aprietan y la densidad se duplica. Si estiras al doble, las marcas se separan y la densidad baja a la mitad. Es como la conservación de masa: la probabilidad total nunca cambia, solo se redistribuye.',
      subtitleCues: [
        { time: 0.0, text: 'Imagina una regla elástica con marcas uniformes' },
        { time: 0.12, text: 'Comprimir la regla → marcas más juntas' },
        { time: 0.25, text: 'Densidad se DUPLICA al comprimir a la mitad' },
        { time: 0.4, text: 'Estirar la regla → marcas más separadas' },
        { time: 0.55, text: 'Densidad se REDUCE a la mitad al estirar al doble' },
        { time: 0.7, text: 'Conservación: la probabilidad total siempre es 1' },
        { time: 0.82, text: 'Como masa en física: se redistribuye, no se crea ni destruye' },
        { time: 0.93, text: 'Base de todo el cambio de variables' },
      ],
      topic: 'Intuición de cambio de variables 1D. Estirar el espacio comprime la densidad. La probabilidad total se conserva. Base para entender el Jacobiano.',
      title: 'Estirar el espacio',
      before: 'Antes: uniforme en [0, 4]',
      after: 'Después: uniforme en [0, 8]',
      densityBefore: 'p(x) = 0.25',
      densityAfter: 'p(x) = 0.125',
      areaLabel: 'Área = 1 siempre',
      insight: 'Conservación de densidad: apretar ↑ estirar ↓',
      compressLabel: 'Comprimir a [0, 2]',
      compressDensity: 'p(x) = 0.5',
      stretchDensity: 'p(x) = 0.125',
      densityDoubles: 'Densidad se DUPLICA',
      densityHalves: 'Densidad se reduce a la MITAD',
    },
    scene2: {
      id: 'Fórmula 1D',
      narration: 'Ejemplo concreto: Z es normal estándar, y f de z es dos z más tres. Para x igual a cinco, la inversa da z igual a uno. La densidad gaussiana en z igual a uno es 0.242, pero la densidad en x igual a cinco es 0.121. La densidad se redujo a la mitad porque f estira el espacio por un factor de dos.',
      subtitleCues: [
        { time: 0.0, text: 'Ejemplo: Z ~ N(0,1), f(z) = 2z + 3' },
        { time: 0.12, text: 'Para x = 5: z = f⁻¹(5) = (5−3)/2 = 1' },
        { time: 0.25, text: 'p_Z(1) = 0.242 (densidad gaussiana en z=1)' },
        { time: 0.38, text: 'f estira el espacio por factor 2 (df/dz = 2)' },
        { time: 0.5, text: 'p_X(5) = p_Z(1) · |1/2| = 0.121' },
        { time: 0.62, text: '¡Densidad reducida a la mitad!' },
        { time: 0.75, text: 'p(x)dx = p(z)dz → p(x) = p(z)·|dz/dx|' },
        { time: 0.88, text: 'El ratio |dz/dx| es la derivada de la inversa' },
      ],
      topic: 'Fórmula de cambio de variables 1D. p_X(x) = p_Z(f⁻¹(x)) · |df⁻¹/dx|. La derivada de f mide cuánto estira/comprime localmente.',
      title: 'Fórmula de cambio de variables',
      zLabel: 'z ~ N(0,1)',
      xLabel: 'x = f(z)',
      stretchLabel: 'f estira aquí',
      compressLabel: 'f comprime aquí',
      proofInterval: '[x, x+dx] → [z, z+dz]',
      proofConserve: 'p(x)dx = p(z)dz',
      proofResult: 'p(x) = p(z) · |dz/dx|',
    },
    scene3: {
      id: 'El Jacobiano',
      narration: 'Imagina una lámina de goma con una Gaussiana pintada. Al estirarla y doblarla, los cuadrados se convierten en paralelogramos. Los lados de cada paralelogramo son las columnas del Jacobiano. El ratio de áreas entre el paralelogramo y el cuadrado original es exactamente el valor absoluto del determinante del Jacobiano.',
      subtitleCues: [
        { time: 0.0, text: 'Lámina de goma con Gaussiana pintada' },
        { time: 0.12, text: 'Estirar y doblar sin romper = invertibilidad' },
        { time: 0.25, text: 'En 2D: cuadrado en z → paralelogramo en x' },
        { time: 0.38, text: 'Lado 1 del paralelogramo = ∂f/∂z₁' },
        { time: 0.5, text: 'Lado 2 del paralelogramo = ∂f/∂z₂' },
        { time: 0.62, text: 'Ambos lados = columnas del Jacobiano J' },
        { time: 0.75, text: 'Área del paralelogramo / Área del cuadrado = |det(J)|' },
        { time: 0.88, text: 'El Jacobiano es la generalización 2D de la derivada' },
      ],
      topic: 'Jacobiano en 2D. Matriz de derivadas parciales J = [∂f/∂x]. Describe cómo una transformación deforma localmente el espacio. Generalización de la derivada 1D.',
      title: 'El Jacobiano en 2D',
      gridBefore: 'Grilla original',
      gridAfter: 'Grilla deformada',
      cellLabel: 'Celda resaltada',
      col1Label: 'col₁ = ∂f/∂z₁',
      col2Label: 'col₂ = ∂f/∂z₂',
      areaRatio: 'Ratio de áreas = |det J|',
      unitSquare: 'Cuadrado unitario',
      parallelogram: 'Paralelogramo',
    },
    scene4: {
      id: 'El determinante',
      narration: 'El determinante del Jacobiano es como el zoom de una cámara. Determinante mayor que uno: estás haciendo zoom out, el espacio se expande. Menor que uno: zoom in, el espacio se comprime. Determinante cero significa que aplastaste la imagen a una línea: perdiste una dimensión y ya no puedes volver atrás.',
      subtitleCues: [
        { time: 0.0, text: '|det J| = factor de cambio de área' },
        { time: 0.12, text: 'Piénsalo como el zoom de una cámara' },
        { time: 0.25, text: 'det > 1: zoom out → expansión' },
        { time: 0.38, text: 'El espacio se estira, la densidad baja' },
        { time: 0.5, text: 'det < 1: zoom in → compresión' },
        { time: 0.62, text: 'El espacio se aprieta, la densidad sube' },
        { time: 0.75, text: 'det = 0: imagen aplastada a una línea' },
        { time: 0.88, text: '¡Dimensión perdida! No invertible' },
      ],
      topic: 'Determinante del Jacobiano. |det J| es el factor de cambio de volumen/área. det>1 expande, det<1 comprime, det=0 colapsa (no invertible). Clave para normalizing flows.',
      title: 'Determinante = cambio de área',
      expand: 'Expansión: |det| > 1',
      compress: 'Compresión: |det| < 1',
      collapse: 'Colapso: det = 0',
      notInvertible: '¡No invertible!',
    },
    scene5: {
      id: 'Composición',
      narration: 'Es como pasar por dos lupas. La primera lupa amplía por dos, la segunda reduce a la mitad. El zoom total es dos por un medio, igual a uno: sin cambio neto. En logaritmos, multiplicar se vuelve sumar: log dos más log un medio es igual a cero. Esta es la magia de componer flujos.',
      subtitleCues: [
        { time: 0.0, text: 'Dos lupas en serie: z → f₁ → h → f₂ → x' },
        { time: 0.12, text: 'Lupa 1: amplía ×2 (det J₁ = 2)' },
        { time: 0.25, text: 'Lupa 2: reduce ×0.5 (det J₂ = 0.5)' },
        { time: 0.38, text: 'Zoom total: 2 × 0.5 = 1 (sin cambio neto)' },
        { time: 0.5, text: 'Regla de la cadena: det(J_total) = det(J₂)·det(J₁)' },
        { time: 0.62, text: 'En log: producto → suma' },
        { time: 0.75, text: 'log|det J| = Σ log|det Jₖ|' },
        { time: 0.88, text: 'log 2 + log 0.5 = 0 ✓' },
      ],
      topic: 'Composición de transformaciones en normalizing flows. Los log-determinantes se suman (regla de la cadena). log p(x) = log p(z₀) − Σ log|det Jₖ|.',
      title: 'Composición de flujos',
      zLabel: 'z ~ N(0,1)',
      hLabel: 'h = f₁(z)',
      xLabel: 'x = f₂(h)',
      logDetSum: 'log|det| se suman',
      chainRule: 'Regla de la cadena',
      detProduct: 'det(J_total) = det(J₂) · det(J₁)',
      logSum: 'log: producto → suma',
      det1: 'det J₁ = 2.0',
      det2: 'det J₂ = 0.5',
      product: '2.0 × 0.5 = 1.0',
      logProduct: 'log 2 + log 0.5 = 0',
    },
    scene6: {
      id: 'La idea del flujo',
      narration: 'Imagina una lámina de goma con una Gaussiana pintada. Cada capa del flujo estira, tuerce o dobla esa lámina, pero nunca la rompe ni la pega. Después de muchas deformaciones, la Gaussiana simple se convierte en cualquier forma compleja. Y como nunca rompimos la lámina, podemos revertir cada paso.',
      subtitleCues: [
        { time: 0.0, text: 'Lámina de goma con Gaussiana pintada' },
        { time: 0.12, text: 'Cada capa: estirar, torcer, doblar' },
        { time: 0.25, text: 'Regla: nunca romper ni pegar (= invertibilidad)' },
        { time: 0.38, text: 'z₀ → f₁ → f₂ → ... → fₖ → x' },
        { time: 0.5, text: 'Gaussiana simple → distribución arbitrariamente compleja' },
        { time: 0.62, text: 'Propiedad 1: invertible (x ↔ z, ida y vuelta)' },
        { time: 0.75, text: 'Propiedad 2: densidad exacta (sin aproximaciones)' },
        { time: 0.88, text: 'Contraste: VAE ≈ aproximada, GAN = sin densidad' },
      ],
      topic: 'Concepto de Normalizing Flow. Cadena de transformaciones invertibles z→f₁→...→fₖ→x. Dos propiedades: invertibilidad y densidad exacta. Contraste con VAEs (aproximada) y GANs (sin densidad).',
      title: 'Normalizing Flows',
      pipeline: 'z₀ → f₁ → f₂ → ... → fₖ → x',
      prop1: 'Invertible: x ↔ z',
      prop2: 'Densidad exacta',
      gaussianLabel: 'Gaussiana simple',
      complexLabel: 'Distribución compleja',
    },
    scene7: {
      id: 'Entrenamiento',
      narration: 'La pérdida tiene dos ingredientes, como una receta. Primer ingrediente: qué tan probable es z bajo la Gaussiana base, es decir, qué tan cerca cayó del centro de la campana. Segundo ingrediente: cuánto estiramos o comprimimos el espacio al llegar ahí. Juntos dan la log-verosimilitud exacta, sin aproximaciones.',
      subtitleCues: [
        { time: 0.0, text: 'La receta de la log-verosimilitud' },
        { time: 0.12, text: 'log p(x) = log p_Z(f⁻¹(x)) + log|det ∂f⁻¹/∂x|' },
        { time: 0.25, text: 'Ingrediente 1: log p_Z(z) — ¿z cerca del centro?' },
        { time: 0.38, text: 'Si z está lejos de la campana, penalización alta' },
        { time: 0.5, text: 'Ingrediente 2: log|det J| — corrección de volumen' },
        { time: 0.62, text: 'Estiramos mucho → penalización; comprimimos → bonus' },
        { time: 0.75, text: 'Juntos: log-verosimilitud EXACTA' },
        { time: 0.88, text: 'Entrenamiento: maximizar esta suma sobre los datos' },
      ],
      topic: 'Entrenamiento de normalizing flows por MLE. log p(x) = log p_Z(f⁻¹(x)) + log|det ∂f⁻¹/∂x|. Dos términos: prior likelihood + volume correction.',
      title: 'Entrenamiento por MLE',
      term1: 'Prior: log p_Z(z)',
      term2: 'Volumen: log|det J|',
      dataLabel: 'Datos',
      contoursLabel: 'Contornos del modelo',
      insight: 'MLE = prior likelihood + corrección de volumen',
      term1Desc: '¿Qué tan probable es z bajo la base?',
      term2Desc: '¿Cuánto estiramos/comprimimos?',
      exactLL: 'Log-verosimilitud exacta',
    },
  },
  en: {
    lessonTitle: 'Change of Variables',
    lessonSubtitle: 'From simple to complex distributions with invertible transforms',
    scene1: {
      id: 'Stretching space',
      narration: 'Think of an elastic ruler with evenly spaced marks. Compress it to half length and the marks crowd together: density doubles. Stretch it to double length and the marks spread apart: density halves. Like conservation of mass in physics: total probability never changes, it only redistributes.',
      subtitleCues: [
        { time: 0.0, text: 'Imagine an elastic ruler with uniform marks' },
        { time: 0.12, text: 'Compress the ruler → marks crowd together' },
        { time: 0.25, text: 'Density DOUBLES when compressed to half' },
        { time: 0.4, text: 'Stretch the ruler → marks spread apart' },
        { time: 0.55, text: 'Density HALVES when stretched to double' },
        { time: 0.7, text: 'Conservation: total probability always equals 1' },
        { time: 0.82, text: 'Like mass in physics: redistributed, never created or destroyed' },
        { time: 0.93, text: 'Foundation of the change of variables formula' },
      ],
      topic: '1D change of variables intuition. Stretching space compresses density. Total probability is conserved. Foundation for understanding the Jacobian.',
      title: 'Stretching space',
      before: 'Before: uniform on [0, 4]',
      after: 'After: uniform on [0, 8]',
      densityBefore: 'p(x) = 0.25',
      densityAfter: 'p(x) = 0.125',
      areaLabel: 'Area = 1 always',
      insight: 'Density conservation: squeeze ↑ stretch ↓',
      compressLabel: 'Compress to [0, 2]',
      compressDensity: 'p(x) = 0.5',
      stretchDensity: 'p(x) = 0.125',
      densityDoubles: 'Density DOUBLES',
      densityHalves: 'Density HALVES',
    },
    scene2: {
      id: '1D formula',
      narration: 'Concrete example: Z is standard normal, f of z equals two z plus three. For x equals five, the inverse gives z equals one. The Gaussian density at z equals one is 0.242, but the density at x equals five is 0.121. Density halved because f stretches space by a factor of two.',
      subtitleCues: [
        { time: 0.0, text: 'Example: Z ~ N(0,1), f(z) = 2z + 3' },
        { time: 0.12, text: 'For x = 5: z = f⁻¹(5) = (5−3)/2 = 1' },
        { time: 0.25, text: 'p_Z(1) = 0.242 (Gaussian density at z=1)' },
        { time: 0.38, text: 'f stretches space by factor 2 (df/dz = 2)' },
        { time: 0.5, text: 'p_X(5) = p_Z(1) · |1/2| = 0.121' },
        { time: 0.62, text: 'Density halved!' },
        { time: 0.75, text: 'p(x)dx = p(z)dz → p(x) = p(z)·|dz/dx|' },
        { time: 0.88, text: 'The ratio |dz/dx| is the derivative of the inverse' },
      ],
      topic: '1D change of variables formula. p_X(x) = p_Z(f⁻¹(x)) · |df⁻¹/dx|. The derivative of f measures local stretching/compression.',
      title: 'Change of variables formula',
      zLabel: 'z ~ N(0,1)',
      xLabel: 'x = f(z)',
      stretchLabel: 'f stretches here',
      compressLabel: 'f compresses here',
      proofInterval: '[x, x+dx] maps to [z, z+dz]',
      proofConserve: 'p(x)dx = p(z)dz',
      proofResult: 'p(x) = p(z) · |dz/dx|',
    },
    scene3: {
      id: 'The Jacobian',
      narration: 'Picture a rubber sheet with a Gaussian painted on it. Stretch and fold it without tearing or gluing. Squares become parallelograms. The sides of each parallelogram are the columns of the Jacobian. The area ratio between the parallelogram and the original square is exactly the absolute value of the Jacobian determinant.',
      subtitleCues: [
        { time: 0.0, text: 'Rubber sheet with a Gaussian painted on it' },
        { time: 0.12, text: 'Stretch and fold without tearing = invertibility' },
        { time: 0.25, text: 'In 2D: square in z → parallelogram in x' },
        { time: 0.38, text: 'Side 1 of parallelogram = ∂f/∂z₁' },
        { time: 0.5, text: 'Side 2 of parallelogram = ∂f/∂z₂' },
        { time: 0.62, text: 'Both sides = columns of the Jacobian J' },
        { time: 0.75, text: 'Area of parallelogram / Area of square = |det(J)|' },
        { time: 0.88, text: 'The Jacobian is the 2D generalization of the derivative' },
      ],
      topic: '2D Jacobian. Matrix of partial derivatives J = [∂f/∂x]. Describes how a transform locally deforms space. Generalization of the 1D derivative.',
      title: 'The Jacobian in 2D',
      gridBefore: 'Original grid',
      gridAfter: 'Warped grid',
      cellLabel: 'Highlighted cell',
      col1Label: 'col₁ = ∂f/∂z₁',
      col2Label: 'col₂ = ∂f/∂z₂',
      areaRatio: 'Area ratio = |det J|',
      unitSquare: 'Unit square',
      parallelogram: 'Parallelogram',
    },
    scene4: {
      id: 'The determinant',
      narration: 'The Jacobian determinant is like a camera zoom. Determinant greater than one: you are zooming out, space expands. Less than one: zooming in, space compresses. Determinant zero means you crushed the image down to a line: you lost a dimension and there is no going back.',
      subtitleCues: [
        { time: 0.0, text: '|det J| = area change factor' },
        { time: 0.12, text: 'Think of it as a camera zoom' },
        { time: 0.25, text: 'det > 1: zoom out → expansion' },
        { time: 0.38, text: 'Space stretches, density drops' },
        { time: 0.5, text: 'det < 1: zoom in → compression' },
        { time: 0.62, text: 'Space squeezes, density rises' },
        { time: 0.75, text: 'det = 0: image crushed to a line' },
        { time: 0.88, text: 'Dimension lost! Not invertible' },
      ],
      topic: 'Jacobian determinant. |det J| is the volume/area change factor. det>1 expands, det<1 compresses, det=0 collapses (not invertible). Key for normalizing flows.',
      title: 'Determinant = area change',
      expand: 'Expansion: |det| > 1',
      compress: 'Compression: |det| < 1',
      collapse: 'Collapse: det = 0',
      notInvertible: 'Not invertible!',
    },
    scene5: {
      id: 'Composition',
      narration: 'It is like looking through two magnifying lenses. The first lens magnifies by two, the second shrinks by half. Total zoom: two times one half equals one, no net change. In logarithms, multiplying becomes adding: log two plus log one half equals zero. This is the magic of composing flows.',
      subtitleCues: [
        { time: 0.0, text: 'Two lenses in series: z → f₁ → h → f₂ → x' },
        { time: 0.12, text: 'Lens 1: magnifies ×2 (det J₁ = 2)' },
        { time: 0.25, text: 'Lens 2: shrinks ×0.5 (det J₂ = 0.5)' },
        { time: 0.38, text: 'Total zoom: 2 × 0.5 = 1 (no net change)' },
        { time: 0.5, text: 'Chain rule: det(J_total) = det(J₂)·det(J₁)' },
        { time: 0.62, text: 'In log: product → sum' },
        { time: 0.75, text: 'log|det J| = Σ log|det Jₖ|' },
        { time: 0.88, text: 'log 2 + log 0.5 = 0' },
      ],
      topic: 'Composition of transforms in normalizing flows. Log-determinants add (chain rule). log p(x) = log p(z₀) − Σ log|det Jₖ|.',
      title: 'Flow composition',
      zLabel: 'z ~ N(0,1)',
      hLabel: 'h = f₁(z)',
      xLabel: 'x = f₂(h)',
      logDetSum: 'log|det| add up',
      chainRule: 'Chain rule',
      detProduct: 'det(J_total) = det(J₂) · det(J₁)',
      logSum: 'log: product → sum',
      det1: 'det J₁ = 2.0',
      det2: 'det J₂ = 0.5',
      product: '2.0 × 0.5 = 1.0',
      logProduct: 'log 2 + log 0.5 = 0',
    },
    scene6: {
      id: 'The flow idea',
      narration: 'Picture a rubber sheet with a Gaussian painted on it. Each flow layer stretches, twists, or bends that sheet, but never tears or glues it. After many deformations, the simple Gaussian becomes any complex shape. And since we never tore the sheet, we can reverse every step.',
      subtitleCues: [
        { time: 0.0, text: 'Rubber sheet with a Gaussian painted on it' },
        { time: 0.12, text: 'Each layer: stretch, twist, bend' },
        { time: 0.25, text: 'Rule: never tear or glue (= invertibility)' },
        { time: 0.38, text: 'z₀ → f₁ → f₂ → ... → fₖ → x' },
        { time: 0.5, text: 'Simple Gaussian → arbitrarily complex distribution' },
        { time: 0.62, text: 'Property 1: invertible (x ↔ z, round trip)' },
        { time: 0.75, text: 'Property 2: exact density (no approximations)' },
        { time: 0.88, text: 'Contrast: VAE = approximate, GAN = no density' },
      ],
      topic: 'Normalizing Flow concept. Chain of invertible transforms z→f₁→...→fₖ→x. Two properties: invertibility and exact density. Contrast with VAEs (approximate) and GANs (no density).',
      title: 'Normalizing Flows',
      pipeline: 'z₀ → f₁ → f₂ → ... → fₖ → x',
      prop1: 'Invertible: x ↔ z',
      prop2: 'Exact density',
      gaussianLabel: 'Simple Gaussian',
      complexLabel: 'Complex distribution',
    },
    scene7: {
      id: 'Training',
      narration: 'The loss has two ingredients, like a recipe. First ingredient: how likely is z under the base Gaussian, that is, how close did it land to the center of the bell curve. Second ingredient: how much did we stretch or compress space to get there. Together they give the exact log-likelihood, no approximations needed.',
      subtitleCues: [
        { time: 0.0, text: 'The log-likelihood recipe' },
        { time: 0.12, text: 'log p(x) = log p_Z(f⁻¹(x)) + log|det ∂f⁻¹/∂x|' },
        { time: 0.25, text: 'Ingredient 1: log p_Z(z) — is z near the center?' },
        { time: 0.38, text: 'If z is far from the bell, heavy penalty' },
        { time: 0.5, text: 'Ingredient 2: log|det J| — volume correction' },
        { time: 0.62, text: 'Stretch a lot → penalty; compress → bonus' },
        { time: 0.75, text: 'Together: EXACT log-likelihood' },
        { time: 0.88, text: 'Training: maximize this sum over the data' },
      ],
      topic: 'Training normalizing flows via MLE. log p(x) = log p_Z(f⁻¹(x)) + log|det ∂f⁻¹/∂x|. Two terms: prior likelihood + volume correction.',
      title: 'Training via MLE',
      term1: 'Prior: log p_Z(z)',
      term2: 'Volume: log|det J|',
      dataLabel: 'Data',
      contoursLabel: 'Model contours',
      insight: 'MLE = prior likelihood + volume correction',
      term1Desc: 'How likely is z under the base?',
      term2Desc: 'How much did we stretch/compress?',
      exactLL: 'Exact log-likelihood',
    },
  },
};

// ── Questions (bilingual) ──

export const questions: Record<Lang, {
  afterDeterminant: import('../../engine/types').QuestionData;
  afterFlowIdea: import('../../engine/types').QuestionData;
}> = {
  es: {
    afterDeterminant: {
      question: 'Si f(z) = 3z + 1 y Z ~ N(0,1), ¿cuál es p_X(4)?',
      choices: ['p_Z(1) = 0.242', 'p_Z(1) / 3 = 0.081', 'p_Z(1) × 3 = 0.726', '0'],
      correctIndex: 1,
      hint: 'f⁻¹(4) = (4−1)/3 = 1. La derivada df/dz = 3, así que |dz/dx| = 1/3.',
      explanation: 'p_X(4) = p_Z(f⁻¹(4)) · |df⁻¹/dx| = p_Z(1) · (1/3) = 0.242/3 ≈ 0.081. f estira por 3, así que la densidad se reduce a un tercio.',
    },
    afterFlowIdea: {
      question: '¿Qué sucede si el determinante del Jacobiano es cero en algún punto?',
      choices: [
        'La densidad se vuelve infinita',
        'La transformación colapsa una dimensión y deja de ser invertible',
        'La densidad se mantiene igual',
        'El flujo se vuelve más expresivo',
      ],
      correctIndex: 1,
      explanation: 'Determinante cero significa que la transformación aplasta el espacio: se pierde una dimensión y ya no se puede invertir.',
    },
  },
  en: {
    afterDeterminant: {
      question: 'If f(z) = 3z + 1 and Z ~ N(0,1), what is p_X(4)?',
      choices: ['p_Z(1) = 0.242', 'p_Z(1) / 3 = 0.081', 'p_Z(1) × 3 = 0.726', '0'],
      correctIndex: 1,
      hint: 'f⁻¹(4) = (4−1)/3 = 1. The derivative df/dz = 3, so |dz/dx| = 1/3.',
      explanation: 'p_X(4) = p_Z(f⁻¹(4)) · |df⁻¹/dx| = p_Z(1) · (1/3) = 0.242/3 ≈ 0.081. f stretches by 3, so density is reduced to one third.',
    },
    afterFlowIdea: {
      question: 'What happens if the Jacobian determinant is zero at some point?',
      choices: [
        'The density becomes infinite',
        'The transform collapses a dimension and is no longer invertible',
        'The density stays the same',
        'The flow becomes more expressive',
      ],
      correctIndex: 1,
      explanation: 'A zero determinant means the transform crushes space: a dimension is lost and inversion is impossible.',
    },
  },
};

export function tx(scene: string, field: string, ...args: (string | number)[]): string {
  const lang = getLang();
  const sceneObj = text[lang]?.[scene];
  const fallbackObj = text.es[scene];
  const raw = (typeof sceneObj === 'object' && sceneObj !== null ? (sceneObj as Record<string, unknown>)[field] : undefined)
           ?? (typeof fallbackObj === 'object' && fallbackObj !== null ? (fallbackObj as Record<string, unknown>)[field] : undefined)
           ?? '';
  let str = String(raw);
  args.forEach((arg, i) => {
    str = str.replace(`$${i + 1}`, String(arg));
  });
  return str;
}
